spring:
  application:
    name: tuneWizard
  ## oracle
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@15.164.103.59:1521:xe
    username: ti_cop
    password: ti_cop1234

chatgpt:
  apikey:
  model: gpt-4o # ?? ?? # ??
openai:
  url:
    model: https://api.openai.com/v1/models
    model-list: https://api.openai.com/vi/models/
    legacy_promt: https://api.openai.com/v1/completions
    prompt: https://api.openai.com/v1/chat/completions

flask:
  url: http://localhost:8088/rag

server:
  port: 8088


# mybatis 매핑 type을 짧게 쓰기 위한 설정
# mapper.xml에서 resultType을 지정할 때 com.god.bo.test.vo.TestVo 대신 TestVo로 간략히 할 수 있다.
mybatis:
  type-aliases-package: com.hanati.cop.tuneWizard.dao
  # mapper.xml 위치 지정
  # **은 하위 폴더 레벨에 상관없이 모든 경로를 뜻하며, *는 아무 이름이나 와도 된다는것을 뜻합니다.
  mapper-locations: mapper/*.xml
